import { pgTable, text, integer, doublePrecision, jsonb, boolean } from "drizzle-orm/pg-core";

export const inventoryItems = pgTable("inventory_items", {
  sku: text("sku").primaryKey(),
  name: text("name").notNull(),
  category: text("category").notNull(),
  qty: doublePrecision("qty").notNull().default(0),
  minQty: doublePrecision("min_qty").notNull().default(0),
  unit: text("unit").notNull(),
  location: text("location").notNull(),
  price: doublePrecision("price").notNull().default(0),
  status: text("status", { enum: ["Disponível", "Alerta", "Crítico"] }).notNull().default("Disponível"),
  imageUrl: text("image_url"),
  weight: doublePrecision("weight"),
  lastUpdated: text("last_updated"),
  stages: jsonb("stages").$type<string[]>().default([]),
  active: boolean("active").notNull().default(true),
  operator: text("operator"),
  purchasePrice: doublePrecision("purchase_price").default(0),
  salesPrice: doublePrecision("sales_price").default(0),
  updatedAt: text("updated_at"),
});

export const productionOrders = pgTable("production_orders", {
  id: text("id").primaryKey(),
  product: text("product").notNull(),
  qty: doublePrecision("qty").notNull().default(1),
  line: text("line").notNull(),
  priority: text("priority").notNull().default("Média"),
  status: text("status").notNull().default("CAD"),
  supervisor: text("supervisor").notNull(),
  progress: integer("progress").notNull().default(0),
  date: text("date").notNull(),
  files: jsonb("files").$type<string[]>().notNull().default([]),
  operator: text("operator"),
  salesOrderId: text("sales_order_id"),
  salesOrderClient: text("sales_order_client"),
  note: text("note"),
  stageSupervisors: jsonb("stage_supervisors").$type<Record<string, string>>().default({}),
  updatedAt: text("updated_at"),
});

export const projectFiles = pgTable("project_files", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  size: text("size").notNull(),
  uploadedBy: text("uploaded_by").notNull(),
  date: text("date").notNull(),
  url: text("url"),
  associatedOP: text("associated_op"),
});

export const salesOrders = pgTable("sales_orders", {
  id: text("id").primaryKey(),
  client: text("client").notNull(),
  clientSegment: text("client_segment"),
  clientDocument: text("client_document"),
  date: text("date").notNull(),
  deliveryDate: text("delivery_date"),
  items: text("items").notNull(),
  total: doublePrecision("total").notNull().default(0),
  status: text("status").notNull().default("Pendente"),
  paymentMethod: text("payment_method").notNull().default("Boleto"),
  paymentStatus: text("payment_status").notNull().default("Pendente"),
  operator: text("operator").notNull(),
  lastOperator: text("last_operator"),
  notes: text("notes"),
  products: jsonb("products").$type<{ sku: string; name: string; qty: number; price: number }[]>().notNull().default([]),
  serialNumber: integer("serial_number"),
  projectFiles: jsonb("project_files").$type<any[]>().default([]),
  projectImages: jsonb("project_images").$type<string[]>().default([]),
  boletoPaid: boolean("boleto_paid").default(false),
  boletoDueDate: text("boleto_due_date"),
  paidAmount: doublePrecision("paid_amount").default(0),
  boletoInstallments: jsonb("boleto_installments").$type<any[]>().default([]),
  commissionPercentage: doublePrecision("commission_percentage").default(0),
  commissionValue: doublePrecision("commission_value").default(0),
  commissionPaid: boolean("commission_paid").default(false),
  commissionPayoutId: text("commission_payout_id"),
  updatedAt: text("updated_at"),
});

export const customers = pgTable("customers", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  document: text("document").notNull(),
  email: text("email").notNull(),
  phone: text("phone").notNull(),
  address: text("address").notNull(),
  city: text("city").notNull(),
  state: text("state").notNull(),
  zip: text("zip").notNull(),
  segment: text("segment"),
  status: text("status"),
  creditBalance: doublePrecision("credit_balance").default(0),
  creditHistory: jsonb("credit_history").$type<any[]>().default([]),
  nickname: text("nickname"),
  updatedAt: text("updated_at"),
});

export const collaborators = pgTable("collaborators", {
  name: text("name").primaryKey(),
  role: text("role").notNull(),
  status: text("status").notNull().default("Ativo"),
  lastLogin: text("last_login"),
  email: text("email").notNull(),
  permissions: jsonb("permissions").notNull(),
  restrictToWorkHours: boolean("restrict_to_work_hours").notNull().default(false),
  accessWindowStart: text("access_window_start").notNull().default("08:00"),
  accessWindowEnd: text("access_window_end").notNull().default("18:00"),
  hideOrderValues: boolean("hide_order_values").default(false),
  pin: text("pin").notNull(),
  allowedTabs: jsonb("allowed_tabs").default([]),
  commissionEligible: boolean("commission_eligible").default(false),
  commissionPercentage: doublePrecision("commission_percentage").default(0),
  updatedAt: text("updated_at"),
});

export const commissionPayouts = pgTable("commission_payouts", {
  id: text("id").primaryKey(),
  collaboratorName: text("collaborator_name").notNull(),
  amount: doublePrecision("amount").notNull().default(0),
  percentage: doublePrecision("percentage").notNull().default(0),
  periodStart: text("period_start").notNull(),
  periodEnd: text("period_end").notNull(),
  paymentDate: text("payment_date").notNull(),
  orderCount: integer("order_count").notNull().default(0),
  salesOrderIds: jsonb("sales_order_ids").$type<string[]>().default([]),
  financialTransactionId: text("financial_transaction_id"),
  notes: text("notes"),
  updatedAt: text("updated_at"),
});

export const purchaseOrders = pgTable("purchase_orders", {
  id: text("id").primaryKey(),
  supplier: text("supplier").notNull(),
  value: doublePrecision("value").notNull().default(0),
  status: text("status").notNull().default("Rascunho"),
  date: text("date").notNull(),
  operator: text("operator"),
  updatedAt: text("updated_at"),
});

export const financialTransactions = pgTable("financial_transactions", {
  id: text("id").primaryKey(),
  description: text("description").notNull(),
  type: text("type").notNull(),
  category: text("category").notNull(),
  amount: doublePrecision("amount").notNull().default(0),
  dueDate: text("due_date").notNull(),
  paymentDate: text("payment_date"),
  status: text("status").notNull().default("PENDENTE"),
  clientOrSupplier: text("client_or_supplier"),
  paymentMethod: text("payment_method"),
  notes: text("notes"),
  salesOrderId: text("sales_order_id"),
  purchaseOrderId: text("purchase_order_id"),
  updatedAt: text("updated_at"),
});

export const systemParameters = pgTable("system_parameters", {
  id: text("id").primaryKey(), // e.g., 'system_config'
  companyName: text("company_name").notNull().default("Estilo Coifas"),
  companyCnpj: text("company_cnpj").notNull().default("12.345.678/0001-90"),
  companyEmail: text("company_email").notNull().default("comercial@estilocoifas.com.br"),
  companyPhone: text("company_phone").notNull().default("(11) 4002-8922"),
  companyAddress: text("company_address").notNull().default("Rua Industrial, 1000 - São Paulo, SP"),
  companyLogo: text("company_logo").default(""),
  defaultCurrency: text("default_currency").notNull().default("BRL"),
  targetProfitMargin: doublePrecision("target_profit_margin").notNull().default(20),
  defaultDeliveryLeadTime: integer("default_delivery_lead_time").notNull().default(15),
  maxDiscountAllowed: doublePrecision("max_discount_allowed").notNull().default(10),
  alertRiskDays: integer("alert_risk_days").notNull().default(3),
  enableDelayAlerts: boolean("enable_delay_alerts").notNull().default(true),
  enableLowStockAlerts: boolean("enable_low_stock_alerts").notNull().default(true),
  enableAutoBackup: boolean("enable_auto_backup").notNull().default(false),
  industrialSegments: jsonb("industrial_segments").$type<string[]>().default([]),
  updatedAt: text("updated_at"),
});
